include:
  # note that this should also include the files needed for `depends_on` (since that key is
  # inherited with `extends`, but the actual files for the services it lists are not)
  - ${PATH_TO_ROOT_DOCKER_PROJ_LOCAL:?}/${PATH_FROM_ROOT_TO_ANUBIS:?}/compose.yaml

services:
  mail_server_anubis:
    container_name: mail_server_anubis
    profiles:
      - ${DOCKER_DEFAULT_PROFILE:?}
    extends:
      file: ${PATH_TO_ROOT_DOCKER_PROJ_LOCAL:?}/${PATH_FROM_ROOT_TO_ANUBIS:?}/compose.yaml
      service: anubis_base
    volumes:
      # container-generated data
      # SYNC: paths in which container produces data (e.g. in config)
      - type: volume
        source: mail_server_anubis_var
        target: /var/anubis/
    environment:
      BIND_NETWORK: unix
      BIND: ${MAIL_SERVER_ANUBIS_IN_SCKT:?}
      TARGET: unix://${MAIL_SERVER_ANUBIS_OUT_SCKT:?}

volumes:
  mail_server_anubis_var:
